apiVersion: v1
kind: Namespace
metadata:
  name: storage-demo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-demo
  namespace: storage-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: storage-demo
  template:
    metadata:
      labels:
        app: storage-demo
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: storage-demo-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: storage-demo
          image: acrarmenlearning2026.azurecr.io/storage-demo@sha256:31b2512dd550ea9e121fdd88890421a5ebccd9891eac88a630077decf5450aa2
          ports:
            - containerPort: 8000

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          envFrom:
            - configMapRef:
                name: storage-demo-config

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL

---
apiVersion: v1
kind: Service
metadata:
  name: storage-demo
  namespace: storage-demo
spec:
  type: ClusterIP
  selector:
    app: storage-demo
  ports:
    - port: 80
      targetPort: 8000
