stages:
  - test

python-test:
  stage: test
  image: python:3.14-slim

  before_script:
    - cd python/storage-demo
    - python -m pip install --upgrade pip
    - python -m pip install -r requirements-dev.txt

  script:
    - python -m compileall -q -x '(\.venv|\.git|\.terraform|__pycache__)' .
    - python -m pytest -q
